// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package kafka

import (
	"github.com/leoguilen/golang-kafka-pubsub/configs"
	"github.com/leoguilen/golang-kafka-pubsub/pkg/eventbus"
)

// Injectors from wire.go:

func Inject(cfg *configs.Config) (eventbus.IEventBus, error) {
	configMap := ProvideKafkaConfig(cfg)
	kafkaEventBus := ProvideKafkaEventBus(configMap)
	return kafkaEventBus, nil
}
